### ISSUE TITLE
Elements with different namespace prefix are detected as DIFFERENT instead of SIMILAR

### ISSUE THREAD

**Issue by drauch** [xmlunit/xmlunit.net#22]
When comparing these two XMLs:

    // Actual = <Root xmlns:x=""http://namespace.com""><x:Elem></x:Elem><x:Elem2></x:Elem2></Root>
    // Expected = <Root xmlns:y=""http://namespace.com""><y:Elem></y:Elem><y:Elem2></y:Elem2></Root>

with "similar" behavior, it should return no differences. But it does report:

    Expected element tag name 'x:Elem' but was 'y:Elem' - comparing <x:Elem...> at /Root[1]/Elem[1] to <y:Elem...> at /Root[1]/Elem[1] (DIFFERENT), Expected element tag name 'x:Elem2' but was 'y:Elem2' - comparing <x:Elem2...> at /Root[1]/Elem2[1] to <y:Elem2...> at /Root[1]/Elem2[1] (DIFFERENT)

Encountered in v2.5. @bodewig has already located the bug, see second-to-last post in https://github.com/xmlunit/user-guide/issues/12 for details.

Best regards,
D.R.

**Comment by bodewig** [comment]
root cause see https://github.com/xmlunit/user-guide/issues/12#issuecomment-337508977

the fix will be to do the same as the Java version - and to write a Unit test :-)

**Comment by bodewig** [comment]
I've just released 2.5.1, it is already available from nuget.org as well as https://github.com/xmlunit/xmlunit.net/releases/tag/v2.5.1

**Comment by drauch** [comment]
Very nice! Thank you for the quick fix! Will give it a try on Monday! 👍

**Comment by renepaul1** [comment]
I still ran into this problem although I was using 2.5.1. Then I tried 2.6.0 and tested with exactly the same xml as referenced above. For me it looks like the issue is still not fixed. 

Error message was: Assert.IsFalse failed. Expected namespace prefix 'x' but was 'y' - comparing <x:Elem...> at /Root[1]/Elem[1] to <y:Elem...> at /Root[1]/Elem[1]
